import type { Metadata } from "next";
import { Young_Serif, Inter } from "next/font/google";
import "./globals.css";

const serif = Young_Serif({
  weight: "400",
  variable: "--font-serif",
  subsets: ["latin"],
});

const sans = Inter({
  weight: "400",
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${serif.variable} ${sans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
